// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLlu-gBkaFgkZQz2XDz1aF2_UWZ80gi3g',
    appId: '1:138412004250:web:e4c3a06f1e1a339ab96023',
    messagingSenderId: '138412004250',
    projectId: 'maps-showcase-dbf24',
    authDomain: 'maps-showcase-dbf24.firebaseapp.com',
    storageBucket: 'maps-showcase-dbf24.firebasestorage.app',
    measurementId: 'G-VZ640D7PFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf3w3QSMPUCpJGrWkN9dv1lHwKsEhjZiY',
    appId: '1:138412004250:android:4d3eef6193dac0f1b96023',
    messagingSenderId: '138412004250',
    projectId: 'maps-showcase-dbf24',
    storageBucket: 'maps-showcase-dbf24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk9DKb-M24QGivC5Ho3C6-EGn7GPNd17g',
    appId: '1:138412004250:ios:69a121a0d1e4a349b96023',
    messagingSenderId: '138412004250',
    projectId: 'maps-showcase-dbf24',
    storageBucket: 'maps-showcase-dbf24.firebasestorage.app',
    iosBundleId: 'com.bobadillaind.googleMapsShowcase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk9DKb-M24QGivC5Ho3C6-EGn7GPNd17g',
    appId: '1:138412004250:ios:69a121a0d1e4a349b96023',
    messagingSenderId: '138412004250',
    projectId: 'maps-showcase-dbf24',
    storageBucket: 'maps-showcase-dbf24.firebasestorage.app',
    iosBundleId: 'com.bobadillaind.googleMapsShowcase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLlu-gBkaFgkZQz2XDz1aF2_UWZ80gi3g',
    appId: '1:138412004250:web:d90ca82b651b5210b96023',
    messagingSenderId: '138412004250',
    projectId: 'maps-showcase-dbf24',
    authDomain: 'maps-showcase-dbf24.firebaseapp.com',
    storageBucket: 'maps-showcase-dbf24.firebasestorage.app',
    measurementId: 'G-1D9C7T4KZ9',
  );
}
